### ISSUE TITLE
module.exports

### ISSUE THREAD

**Issue by sinapirani** [dimdenGD/url-file-size#2]
please edit source in npm.

npm:
let ufs = url => {
    return new Promise((res, rej) => {
        let req = url.startsWith('https://') ? https.get(url) : http.get(url);
        req.once("response", r => {
            req.abort();
            let c = parseInt(r.headers['content-length']);
            if(!isNaN(c)) res(c);
            else rej("Couldn't get file size");
        });
        req.once("error", e => rej(e));
    });
};

delete (let ufc) and add module.export

**Comment by dimdenGD** [comment]
Weird how I didn't notice this before, thanks
