### ISSUE TITLE
ERR_INVALID_URL on github links

### ISSUE THREAD

**Issue by slavikator** [dimdenGD/url-file-size#4]
Doesn't work on GitHub links.

Examples that don't work:
https://github.com/Kong/insomnia/releases/download/lib%403.5.0/inso-macos-3.5.0.zip
https://github.com/httptoolkit/httptoolkit-desktop/releases/download/v1.10.1/HttpToolkit-1.10.1.dmg
https://github.com/RoyalIcing/Lantern/archive/refs/tags/1.1.0.tar.gz
https://github.com/720kb/ndm/releases/download/v1.2.0/ndm-1.2.0.dmg

```
  code: 'ERR_INVALID_URL'
```

**Comment by dimdenGD** [comment]
This happens because github uses redirects. I have updated the package to support redirects on npm and github and it should work now.
