### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by hernanif1** [dimdenGD/url-file-size#6]
See the example:
https://codesandbox.io/s/icy-sea-d9fjcp?file=/src/App.js

![Screenshot 2023-01-02 at 16 36 46](https://user-images.githubusercontent.com/1771727/210252553-ee4bbe3f-f174-4bdc-b54b-4e34b5a15edf.png)

**Comment by dimdenGD** [comment]
This package is not made for browsers, it is Node.js only.
